version: "3.3"
services:
    dynamodb:
        image: soichi777/dynamodb_local
        ports: 
            - "7777:8000"
    tweetcollector:
        build: ./target/docker/stage
        image: tweetcollector
        environment:
            - JAVA_OPTS
        depends_on: 
            - dynamodb
        links:
            - dynamodb


